export const COUNTER_INCREMENT="COUNTER_INCREMENT"
export const COUNTER_DECREMENT = "COUNTER_DECREMENT"

export const CART_COUNT ="CART_COUNT"
export const ADD_TODOS ="ADD_TODOS"
export const DELETE_TODOS = "DELETE_TODOS"